name: Multi-Product Price Checker

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Fetch last_prices.json from data branch
        run: |
          git fetch origin data
          git checkout origin/data -- last_prices.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run price tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
        run: |
          python price_tracker.py

      - name: Push updated last_prices.json to data branch
        if: success()
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          set -e

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch
          git checkout data || git checkout -b data

          git add last_prices.json
          git commit -m "Update last prices" || echo "No changes to commit"

          git remote -v

          git remote remove origin
          git remote add origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}

          git remote -v

          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:data
